on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release version"
        type: choice
        required: true
        options:
          - 2.7.3 14.19.3
          - 2.7.2 14.19.1
          - 2.7.1 14.19.1
          - 2.7 14.19.1
          - 2.6.1 14.18.3
          - 2.6 14.18.3
          - 2.5.8 14.19.3
          - 2.5.7 14.19.3
          - 2.5.6 14.18.3
          - 2.5 14.18.1
          - 2.4 14.17.6
          - 2.3.6 14.17.6
          - 2.3.5 14.17.5
          - 2.3.4 14.17.4
          - 2.3.3 14.17.4
          - 2.3.2 14.17.3
          - 2.3.1 14.17.3
          - 2.2.4 12.22.5
          - 2.2.3 12.22.5

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: echo "RELEASE=$(echo ${{ inputs.release }} | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - run: echo "NODE_VERSION=$(echo ${{ inputs.release }} | cut -d ' ' -f 2)" >> $GITHUB_ENV
      - run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/meteor:${{ env.RELEASE }}-bullseye-slim" >> $GITHUB_ENV
      - run: echo "${{ github.token }}" | docker login ghcr.io --username $ --password-stdin
      - run: DOCKER_BUILDKIT=1 docker build --build-arg RELEASE=${{ env.RELEASE }} --build-arg NODE_VERSION=${{ env.NODE_VERSION }} --tag ${{ env.IMAGE_NAME }} .
      - run: docker push ${{ env.NODE_VERSION }}
