on:
  workflow_dispatch:
  schedule: [{ cron: 0 0 * * * }] # “At 00:00.” see https://crontab.guru/#0_0_*_*_*

jobs:
  publish-all:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    strategy:
      matrix:
        release:
          - "3.2"
          - "3.1.2"
          - "3.1.1"
          - "3.1"
          - "3.0.4"
          - "3.0.3"
          - "3.0.2"
          - "3.0.1"
          - "3.0"
          - "2.16"
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.token }}" | docker login ghcr.io --username $ --password-stdin
      - run: DOCKER_BUILDKIT=1 docker build --pull --push --build-arg RELEASE=${{ matrix.release }} --tag ghcr.io/${{ github.repository_owner }}/meteor:${{ matrix.release }} .
